name: emkapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.2
  async: ^2.6.1
  image_cropper: ^1.4.0
  multi_image_picker: ^4.8.1
  sqflite:
  collection: ^1.15.0
  path:
  jiffy: ^4.1.0
  path_provider: ^2.0.2
  intl: ^0.17.0
  shared_preferences: 
  http:
  provider: ^5.0.0
  charts_flutter: ^0.10.0
  fl_chart: ^0.36.1
  get_it: ^7.1.3
  flutter_form_builder: ^6.0.1
  phone_number: ^0.11.0
  matrix_gesture_detector: ^0.1.0
  fab_circular_menu: ^1.0.2
  #week_of_year: ^1.0.1
  progress_dialog: ^1.2.4
  expandable: ^5.0.1
  expandable_group : ^0.0.7
  flutter_rounded_date_picker: ^2.0.2
  percent_indicator: ^2.1.7+2
  #firebase_auth:
  #archive: ^3.1.2
  #flutter_archive: ^4.0.1
  #rename: ^1.2.0

  #overlay: ^0.0.1

  animate_icons:

  dropdown_date_picker: ^0.1.1+2

  draggable_fab: ^0.1.1

  share: ^2.0.2

  email_validator: ^2.0.1

  transparent_image: ^2.0.0

  cached_network_image: ^3.0.0

  flutter_staggered_grid_view: ^0.4.0

  auto_size_text: ^2.1.0

  image_gallery_saver: ^1.6.9

  flutter_speed_dial: ^3.0.5

  marquee: ^2.1.0

  states_rebuilder: ^4.1.0+2

  animator: ^3.0.0

  record_mp3: ^3.0.0

  audioplayers: ^0.20.1

  #flutter_audio_query:

  audio_manager: ^0.8.2

  flutter_colored_progress_indicators: ^1.2.0

  network_to_file_image: ^3.0.0

  printing: ^5.2.1

  permission_handler: ^8.3.0

  pdf: ^3.3.0

  file_picker: ^4.2.4

  #video_player:

  #media_info: ^0.9.0

  video_thumbnail: ^0.4.3 

  open_file: ^3.2.1  

  webview_flutter: ^2.0.7

  url_launcher : ^6.0.9

  flutter_filereader: ^3.0.0


  flutter_sms: ^2.3.1

  font_awesome_flutter: ^9.1.0

  flutter_inappwebview: ^5.3.2

  flutter_js: 0.5.0+3

  syncfusion_flutter_pdfviewer: 19.2.62-beta

  dio : ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dependency_overrides:
  file: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"


flutter_icons:
  image_path: "assets/images/CSI3.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    - assets/images/
    - assets/colors.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
